### ISSUE TITLE
Unable to display time on Smith Chart tooltip

### ISSUE THREAD

**Issue by WaleedNaveed** [syncfusion/ej2-react-samples#17]
I am using Smith Chart control of SyncFusion. The tooltip of Smith Chart only shows the resistance and reactance values. Screen-shot:

![SmithChart](https://user-images.githubusercontent.com/35847314/76507788-3154a600-646f-11ea-9bb1-01b81de0294a.PNG)

I also want to display the time in the tooltip. How can i show the time in tooltip ?
The data which my query returns is an array in which an object has the following format:
                                          **[DateTime, Resistance, Reactance]**

From this array i extract the **resistance** and **reactance** values to create an array of points which is then passed to the **points of SmithChartComponent**. Now when i hover over any point i get the tooltip like the one shown above. How can i also display time in the tooltip ?

My code is:

```
do {
      series.push(
        <SmithchartSeriesDirective
          key={this.smithChartId}
          name={Smith-Chart}
          points={this.listResult[index]}
          tooltip={{ visible: true}}>
        </SmithchartSeriesDirective>
      );
      index++;
    }
    while (this.listResult.length > index)
    return (
      <div className='control-pane'>
        <div className='col-md-12 control-section'>
          <SmithchartComponent 
            id={this.smithChartId}
            ref={gauge => (this.smithchartInstance = gauge as SmithchartComponent)}
            legendSettings={{ visible: true, shape: 'Circle', position: ''top }}>
            <Inject services={[SmithchartLegend, TooltipRender]} />
            <SmithchartSeriesCollectionDirective>
              {series}
            </SmithchartSeriesCollectionDirective>
          </SmithchartComponent>
        </div>
      </div>);
```

How can i customize the tooltip so that i can also display the **DateTime** of the point in the tooltip.

**Comment by sreharii** [comment]
Hi Waleed,

We have analyzed your query. From that, we would like to let you know that as of now we don’t have support for “**customizing tooltip content through the event**”. We consider this scenario as improvement and we have logged a feature request on this. It can be tracked through our feedback portal below. 
 
**Feedback Portal:** https://www.syncfusion.com/feedback/12761

The fix will be available in our upcoming volume 1 main release which expected to be rolled out at the end of March 2020.
 
If you have any more specifications/suggestions to the feature request, you can add it as a comment in the portal. 

Regards,
Srihari M

**Comment by sriharii** [comment]
Hi Waleed, 
  
Thanks for being patience.
  
We are glad to announce that our v18.1.44  patch release is rolled out, we have added the fix for the reported issue and is available for download under the following link.  

Npm Packages: https://www.npmjs.com/~syncfusionorg  
 
We appreciate your patience in waiting for this release. Let me know if you need further assistance.  
  
Regards,  
Srihari M

**Comment by WaleedNaveed** [comment]
Hi Srihari M,

Thanks for the update. Can you kindly give an example of how to use this feature or any documentation link ? I am unable to find the documentation link or any example of specified issue.

Thanks

**Comment by WaleedNaveed** [comment]
Hello Srihari M,

I am still unable to resolve my problem of tooltip. At first i tried to update **syncfusion/ej2-charts** package from [https://www.npmjs.com/package/@syncfusion/ej2-charts](url), then i tried with **syncfusion/ej2** but could not get the required result.

Let me show you my code:

```
series.push(
        <SmithchartSeriesDirective
          key={this.smithChartId}
          fill={this.props.options.smithChartSeriesConfiguration[index].linesColor}
          width={this.props.options.smithChartSeriesConfiguration[index].showMarkerLines ? 1 : 0}
          name={this.props.options.smithChartSeriesConfiguration[index].legendText}
          points={this.listResult[index]}
          animationDuration='1000'
          enableAnimation={this.props.options.smithChartSeriesConfiguration[index].showAnimation}
          tooltip={{ visible: this.props.options.smithChartSeriesConfiguration[index].showToolTip }}
          marker={{
            fill: this.props.options.smithChartSeriesConfiguration[index].markerColor,
            shape: 'Circle',
            visible: this.props.options.smithChartSeriesConfiguration[index].showMarker,
            dataLabel: { visible: this.props.options.smithChartSeriesConfiguration[index].showDataLabel },
            border: { color: this.props.options.smithChartSeriesConfiguration[index].markerBorderColor, width: this.props.options.smithChartSeriesConfiguration[index].markerBorderWidth }
          }}
        >
        </SmithchartSeriesDirective>
      );
```
I am storing **this.listResult** array in **points** array, each object in **this.listResult** has three fields (dateandtime, reactance, resistance) i.e.

![pic2](https://user-images.githubusercontent.com/35847314/82251516-c50e8b00-9966-11ea-99ba-015790009383.PNG)

But when i run the code, i only get the **resistance** and **reactance** in the tooltip i.e. 

![pic1](https://user-images.githubusercontent.com/35847314/82251950-96dd7b00-9967-11ea-9b4f-e7aa939d6e0a.PNG)

I also want to show the **dateandtime** field in the tooltip. How can i achieve this ?

**Comment by tianying0525** [comment]
Hi Waleed,

I am also trying to get customized tooltip of smith chart by using SyncFusion's package but got no luck. I wonder if you have figured this out? 

Thx.

**Comment by WaleedNaveed** [comment]
Hi @tianying0525 , no, could not figure it out yet. Waiting for SyncFusion's reply.

**Comment by tianying0525** [comment]
@WaleedNaveed Thx for your reply. I will also wait then since it's the best smith chart implementation I can find online.

**Comment by Swetha-Babu** [comment]
Hi Waleed,

Greetings from Syncfusion.

We can render the custom tooltip with the current date and time using the tooltipRender event in Charts component. However, we have created the simple react application to demonstrate the same, and please find the below stackblitz link for your sample reference.

Sample link: https://stackblitz.com/edit/react-qtadwz

Code Snippet:
```
renderTooltip(args) {
        var currentDate = new Date();
        var datetime = currentDate.getDate() + "/"
                + (currentDate.getMonth()+1)  + "/" 
                + currentDate.getFullYear() + " - "  
                + currentDate.getHours() + ":"  
                + currentDate.getMinutes() + ":" 
                + currentDate.getSeconds();
        args.text = datetime.toString();
    }

<SmithchartComponent tooltipRender={this.renderTooltip.bind(this)} id='smith-chart' ref={gauge => this.smithchartInstance = gauge} legendSettings={{ visible: true, shape: 'Circle' }}>
                        <Inject services={[SmithchartLegend, TooltipRender]}/>
</SmithchartComponent>
```
Kindly, revert us if you have any concerns.

Regards,
Swetha
