### ISSUE TITLE
I need to customize the export to excel funcionality

### ISSUE THREAD

**Issue by tejaspda** [syncfusion/ej2-react-samples#30]
Hi 

I have requirement to customize the excel to export functionality in Grid while exporting the file I can add another sheet and write certain list of given filter on the fly on that other sheet. Is this possible in syncfusion Grid component that I can write in excel other sheet before dowloading or exporting.

**Comment by rajapandiravi1009** [comment]
Hi Tejaspda,

Greetings from Syncfusion support

We have checked your query and we understand that while exporting the Grid, you like to create the New sheet in the excel document and write some content based on your requirement. Based on your query we have prepared a sample and we have achieved your requirement by binding the finalPageSetup internal event in the Created event of Grid. Please refer the below code example and sample for more information.


````
```
function created() { //created event of Grid
      
      gridInstance.on('finalPageSetup', finalPageSetup)
    }

function finalPageSetup(args) {
      args.worksheets[1] =  {
        columns: [
          // define the columns you want in the cover page
          {
            index: 1,
            width: 120,
          },
        ],
        enableRtl: false,
        images: [],
        rows: [
          // define the rows you want in the cover page
          {
            index: 1,
            cells: [
              {
                index: 1,
                value: 'Set your custom content here',
                styles: {
                  bold: true,
                  borders: { color: '#E0E0E0' },
                  fontSize: 12,
                  hAlign: 'right',
                },
              },
            ],
          },
          {
            index: 2,
            cells: [
              {
                index: 1,
                value: 'Set your custom content here',
                styles: {
                  bold: true,
                  borders: { color: '#E0E0E0' },
                  fontSize: 12,
                  hAlign: 'right',
                },
              },
            ],
          },
          {
            index: 3,
            cells: [
              {
                index: 1,
                value: 'Set your custom content here',
                styles: {
                  bold: true,
                  borders: { color: '#E0E0E0' },
                  fontSize: 12,
                  hAlign: 'right',
                },
              },
            ],
          },
        ],
      }
    }

--
```
````


Sample: https://stackblitz.com/edit/react-zqizyk?file=index.js,index.html

API: https://helpej2.syncfusion.com/react/documentation/api/grid/#created

**Comment by gsumankumar** [comment]
Hi @tejaspda , 
I hope the provided sample meets your requirements. Please feel free to let me know if you have any additional inquiries or requests.

**Comment by gsumankumar** [comment]
This issue has been inactive for over a week, so we are closing it for housekeeping purposes. If you have any additional information to assist us or concerns on shared sample, please reopen the issue. Thank you for your understanding.
