### ISSUE TITLE
Unable to properly run the demo example from GitHub;

### ISSUE THREAD

**Issue by milosKomiRajkovic94** [syncfusion/ej2-react-samples#7]
-Following instructions from the description of this repository, I wasn't able to completely run this project locally, I have done:

1. npm install
2. I tried npm run build but I got error: "Error: ENOENT: no such file or directory, open './src/common/api-table'";
3. I found api-table JSON file from "Essential studio"/"React"/"Explore demo source" option;
4. Again I run npm run build but I got style error that I need to do "npm rebuild node-sass";
5. I have done npm rebuild node-sass;
6. I ran npm run build again, now the build passes but with a lot of errors and one of the errors are:

"ERROR in ./src/diagram/default-functionality.js
Module not found: Error: Can't resolve '@syncfusion/ej2-react-diagrams' in 'C:\Users\Jiway\Downloads\ej2-react-samples-master\ej2-react-samples-master\src\diagram'
 @ ./src/diagram/default-functionality.js 14:27-68
 @ ./src/diagram/diagram-routes.js
 @ ./src/common/all-routes.js
 @ ./src/common/component-content.js
 @ ./src/common/index.js"

7. When I run index.html I get an error:

Uncaught Error: Cannot find module "@syncfusion/ej2-react-diagrams"

What should I do next in order to resolve this problem and to run the project properly?

**Comment by ilanfreoua** [comment]
same thing ..

ReferenceError: primordials is not defined

**Comment by kumaresan-subramani** [comment]
> same thing ..
> 
> ReferenceError: primordials is not defined

HI @ilanfreoua ,

Thanks for contacting Syncfusion.

We suspect you're using node 12 and gulp 3. That combination does not work: https://github.com/gulpjs/gulp/issues/2324


**Solution**: 

please do Either upgrade to gulp 4 or downgrade to an earlier node.

**Comment by kumaresan-subramani** [comment]
> -Following instructions from the description of this repository, I wasn't able to completely run this project locally, I have done:
> 
> 1. npm install
> 2. I tried npm run build but I got error: "Error: ENOENT: no such file or directory, open './src/common/api-table'";
> 3. I found api-table JSON file from "Essential studio"/"React"/"Explore demo source" option;
> 4. Again I run npm run build but I got style error that I need to do "npm rebuild node-sass";
> 5. I have done npm rebuild node-sass;
> 6. I ran npm run build again, now the build passes but with a lot of errors and one of the errors are:
> 
> "ERROR in ./src/diagram/default-functionality.js
> Module not found: Error: Can't resolve '@syncfusion/ej2-react-diagrams' in 'C:\Users\Jiway\Downloads\ej2-react-samples-master\ej2-react-samples-master\src\diagram'
> @ ./src/diagram/default-functionality.js 14:27-68
> @ ./src/diagram/diagram-routes.js
> @ ./src/common/all-routes.js
> @ ./src/common/component-content.js
> @ ./src/common/index.js"
> 
> 1. When I run index.html I get an error:
> 
> Uncaught Error: Cannot find module "@syncfusion/ej2-react-diagrams"
> 
> What should I do next in order to resolve this problem and to run the project properly?

HI @milosKomiRajkovic94 ,

Thanks for reporting this issue.

We have resolved all reported issues. Please check now and let us know if you have any other concerns.

**Comment by milosKomiRajkovic94** [comment]
Hi @kumaresan-subramani ,

thank you, I trust you it is ok, I honestly after more than a year forgot what I wanted to test with this repo, so it is ok for me. I will close the question thread.

Best regards,
Miloš Rajković!
